

pinentryVersion=$(sed -nE '/^#define VERSION "([0-9]\.[0-9]+\.[0-9]+)"$/{s//\1/p;q;}' < "$(dirname "${BASH_SOURCE[0]}")/Source/pinentry-current/config.h")

if [[ -z "$pinentryVersion" ]] ;then
	echo "Unable to find pinentry version!" >&2
	exit 1
fi

PRERELEASE=b1

COMMIT_HASH=$(git rev-parse --short HEAD)$(test -z "$(git status --porcelain)" || echo "+")
VERSION="${pinentryVersion}${PRERELEASE} ($COMMIT_HASH)"
BUILD_VERSION=0n
